[package]
name = "cjstream"
version = "0.0.1"
edition = "2021"

[lib]

[dependencies]
crossbeam = "0.8.4"
dotenvy = "0.15.7"
flate2 = "1.0.35"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
struson = "0.6.0"

[dev-dependencies]
tempfile = "3.2"
